language: python

python:
  - "3.5"
  - "3.4"

install:
  - pip install numpy

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - cp build/libkdtree* python/libkdtree
  - python3 python/test.py